// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOLWOrcIGXFIVQJ1LB2wIPy5hZhzlt1Ck',
    appId: '1:230888413088:android:5cd607a276d591cfa3b6c5',
    messagingSenderId: '230888413088',
    projectId: 'festival-2e218',
    databaseURL: 'https://festival-2e218-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'festival-2e218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1og1ScJ8vz518kWsJ278rOZL6ReUJqoQ',
    appId: '1:230888413088:ios:9157aef0ef58a12da3b6c5',
    messagingSenderId: '230888413088',
    projectId: 'festival-2e218',
    databaseURL: 'https://festival-2e218-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'festival-2e218.appspot.com',
    iosClientId: '230888413088-uf1ms5m95vh1q8jtcm6np8fd5gm8e7t4.apps.googleusercontent.com',
    iosBundleId: 'hu.bitclub.festival',
  );
}
